INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 28, in hello
    app.loggging.info('Main request successful!')
AttributeError: 'Flask' object has no attribute 'loggging'
INFO:werkzeug:127.0.0.1 - - [15/Jun/2021 08:56:04] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/guanqing/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 28, in hello
    app.loggging.info('Main request successful!')
AttributeError: 'Flask' object has no attribute 'loggging'
INFO:werkzeug:127.0.0.1 - - [15/Jun/2021 08:56:16] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:app:Main request successful!
INFO:werkzeug:127.0.0.1 - - [15/Jun/2021 08:57:06] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:werkzeug: * Restarting with fsevents reloader
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 117-169-593
INFO:app:Main request successful!
INFO:werkzeug:127.0.0.1 - - [15/Jun/2021 08:59:46] "[37mGET / HTTP/1.1[0m" 200 -
INFO:app:Status request successful!
INFO:werkzeug:127.0.0.1 - - [15/Jun/2021 08:59:52] "[37mGET /status HTTP/1.1[0m" 200 -
